- name: base packages
  yum: name='{{ item }}' state=present
  with_items:
         - bzip2
         - bzip2-libs
         - gcc
         - git
         - munge-libs
         - munge-devel
         - readline-devel
         - perl
         - pam-devel
         - rpm-build
         - vim
         - wget
