- name: base packages
  yum: name='{{ item }}' state=present
  with_items:
         - autoconf
         - bzip2
         - bzip2-devel
         - bzip2-libs
         - gcc
         - git
         - readline-devel
         - openssl-devel
         - perl
         - pam-devel
         - rpm-build
         - vim
         - wget
         - zlib-devel
