- name: base packages
  yum: name='{{ item }}' state=present
  with_items:
         - autoconf
         - automake
         - bzip2
         - bzip2-devel
         - bzip2-libs
         - libtool
         - mariadb
         - mariadb-devel
         - mariadb-libs
         - gcc
         - git
         - readline-devel
         - openssl-devel
         - perl
         - perl-ExtUtils-MakeMaker
         - pam-devel
         - rpm-build
         - vim
         - wget
         - zlib-devel
