- name: base packages
  yum: name='{{ item }}' state=present
  with_items:
         - autoconf
         - automake
         - bind-utils
         - bzip2
         - bzip2-devel
         - bzip2-libs
         - "wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
         - libtool
         - mariadb
         - mariadb-devel
         - mariadb-libs
         - mlocate
         - gcc
         - git
         - readline-devel
         - openssl-devel
         - perl
         - perl-ExtUtils-MakeMaker
         - pam-devel
         - python2-pip
         - rpm-build
         - vim
         - wget
         - zlib-devel

- name: pip packages
  pip: 
    name: flask
- name: pip packages
  pip: 
    name: flask-wtf
