- name: set up slurm files 
  file:
    path: /var/spool/slurm 
    mode: '0755'
    state: directory
    owner: slurm
    group: slurm

- name: slurm directory
  file:
    path: /etc/slurm
    mode: '0755'
    state: directory
    owner: slurm
    group: slurm

- name: set up slurm config
  copy:
    src: etc/slurm/slurm.conf
    dest: /etc/slurm/slurm.conf
    mode: '0644'
    owner: slurm
    group: slurm

- name: set up munge key
  copy:
    src: etc/munge/munge.key
    dest: /etc/munge/munge.key
    mode: '0400'
    owner: munge
    group: munge

- name: munge service
  service:
    name: munge
    state: started
