- name: set up slurm files 
  file:
    path: /var/spool/slurm 
    mode: '0755'
    state: directory
    owner: slurm
    group: slurm

- name: set up slurm config
  file:
    src: etc/slurm/slurm.conf
    dest: /etc/slurm/slurm.conf
    mode: '0644'
    owner: slurm
    group: slurm
