- name: start slurmctld
  service:
    name: slurmctld
    state: started

- name: install create_instance script
  copy:
    src: usr/sbin/create_instance.py
    dest: /usr/sbin/create_instance.py
    mode: '0755'

- name: install start_instance script
  copy:
    src: usr/sbin/start_instance.py
    dest: /usr/sbin/start_instance.py
    mode: '0755'

- name: install stop_instance script
  copy:
    src: usr/sbin/stop_instance.py
    dest: /usr/sbin/stop_instance.py
    mode: '0755'

- name: install configure_node script
  copy:
    src: usr/sbin/configure_node.sh
    dest: /usr/sbin/configure_node.sh
    mode: '0755'

- name: install bootstrap_node script
  copy:
    src: usr/sbin/bootstrap_node.sh
    dest: /usr/sbin/bootstrap_node.sh
    mode: '0755'
