#!/bin/bash

if [[ $UID -ne 0 ]]; then
	echo "Error! You must be root!"
	exit
fi

cd /root/cluster/ansible/
git pull

ansible-playbook common.yml node.yml -i `hostname` --vault-password-file=/root/.vaultpass
